#!/bin/sh

set -e

if [[ -n "$1" ]]; then
    COMMAND="$1"
    shift
fi

GH_REPO_OWNER=neovim
GH_REPO_NAME=neovim
LOCAL_REPO_NAME=neovim

DEBIAN_VERSION=$(cat /etc/debian_version)
IMAGE_FULL_NAME="cpp-builder:custom-$DEBIAN_VERSION"
if [[ "$COMMAND" == "--rebuild" ]] || [[ -z "$(docker image ls --filter reference="$IMAGE_FULL_NAME" -q)" ]]; then
    docker pull debian:$DEBIAN_VERSION
    docker build --build-arg DEBIAN_VERSION=$DEBIAN_VERSION -t $IMAGE_FULL_NAME build
fi

if ! [[ -d $LOCAL_REPO_NAME ]]; then
    git clone https://github.com/GH_REPO_OWNER/GH_REPO_NAME.git
fi

git -C $LOCAL_REPO_NAME clean -Xdf
git -C $LOCAL_REPO_NAME fetch

HIGHEST_VERSION_TAG=$(git -C $LOCAL_REPO_NAME tag | awk -f compare.awk)
echo "Highest version = $HIGHEST_VERSION_TAG"

git -C $LOCAL_REPO_NAME checkout tags/$HIGHEST_VERSION_TAG
git -C $LOCAL_REPO_NAME pull origin tags/$HIGHEST_VERSION_TAG

docker run --rm -u $(id -u):$(id -g) -v ./$LOCAL_REPO_NAME:/$LOCAL_REPO_NAME $IMAGE_FULL_NAME
